version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "homepage-capture-s3-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jdyonxtr76zc"
s3_prefix = "homepage-capture-s3-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CaptureUrl=\"https://www-test.bu.edu/homepage-alt/?is_buhp_scrape=true\" S3BucketName=\"buaws-websites-homepage-test\" S3Path=\"\" SubdirPrefix=\"home\""
image_repositories = []

[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "websites-homepage-capture-s3-test"
s3_prefix = "websites-homepage-capture-s3-test"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
tags = "Service=\"websites\" Function=\"homepage\" Landscape=\"test\" CostCenter=\"AWS Websites\""
parameter_overrides = [
  "CaptureUrl=https://www-test.bu.edu/homepage-alt/?is_buhp_scrape=true",
  "S3BucketName=websites-homepage-capture-s3-test-files",
  "S3Path=\"\"",
  "SubdirPrefix=home"
]
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "websites-homepage-capture-s3-prod"
s3_prefix = "websites-homepage-capture-s3-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
tags = "Service=\"websites\" Function=\"homepage\" Landscape=\"prod\" CostCenter=\"AWS Websites\""
parameter_overrides = [
  "CaptureUrl=https://www.bu.edu/homepage-alt/?is_buhp_scrape=true",
  "S3BucketName=websites-homepage-capture-s3-prod-files",
  "S3Path=\"\"",
  "SubdirPrefix=home"
]
image_repositories = []

# IAM Role

[iam-test]
[iam-test.deploy]
[iam-test.deploy.parameters]
template_file = "iam-role-template.yml"
stack_name = "websites-homepage-capture-s3-test-role"
s3_prefix = "websites-homepage-capture-s3-test-role"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
tags = "Service=\"websites\" Function=\"homepage\" Landscape=\"test\""
parameter_overrides = [
  "GithubActionsRoleName=websites-homepage-capture-s3-test-GithubActionsCloudFormingRole",
  "RepoName=page-capture-s3",
  "Branch=test",
  "StackPrefix=websites-homepage-capture"
]
image_repositories = []


[iam-prod]
[iam-prod.deploy]
[iam-prod.deploy.parameters]
template_file = "iam-role-template.yml"
stack_name = "websites-homepage-capture-s3-prod-role"
s3_prefix = "websites-homepage-capture-s3-prod-role"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
tags = "Service=\"websites\" Function=\"homepage\" Landscape=\"prod\""
parameter_overrides = [
  "GithubActionsRoleName=websites-homepage-capture-s3-prod-GithubActionsCloudFormingRole",
  "RepoName=page-capture-s3",
  "Branch=prod",
  "StackPrefix=websites-homepage-capture"
]
image_repositories = []
